FROM docker.io/library/ubuntu:22.04

ENV DEBIAN_FRONTEND=noninteractive
RUN apt-get update && apt-get install -y --no-install-recommends \
        build-essential ca-certificates ccache cmake gcc-arm-none-eabi git \
        libnewlib-arm-none-eabi libstdc++-arm-none-eabi-newlib python3 python3-pip \
    && rm -rf /var/lib/apt/lists/*
RUN pip3 install --no-cache-dir littlefs-python==0.4.0

WORKDIR /src
